### ISSUE TITLE
TODO: RSS Feeds

### ISSUE THREAD

**Issue by adamhstewart** [adamhstewart/gizra-hugo#16]
the idea is that we want to be able to reproduce the existing feeds so that we don't have to update the consumers

`/rss.xml`
`/rss-drupal.xml`
`/rss-elm.xml`
`/rss-itunes.xml`

Hugo by default publishes feeds at `/[Section]/index.xml` - we need to override that.

**Comment by adamhstewart** [comment]
I merged the existing PR because it was needing constant re-roll with other changes to posts.  It was just (a) converting the "more" tags to Hugo format and (b) adding a template for all RSS feeds.

The whole issue of redefining the feeds to be relative to root directory seems a bit complex: https://discourse.gohugo.io/t/how-can-i-change-the-rss-url/118

**Comment by adamhstewart** [comment]
Update:

This designates there to be an RSS output in the root directory and removes them from the Section directories:

```yaml
outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"
```

To do: 
- Get multiple feeds in the root directory
- Override the template to get the proper feeds

**Comment by adamhstewart** [comment]
This works to rename the feed:
```yaml
outputFormats:
  RSS:
    mediaType: "application/rss"
    baseName: "rss"
```

But as you'd probably expect, this does not create multiple feeds (the first is just overridden by the second):

```yaml
outputFormats:
  RSS:
    mediaType: "application/rss"
    baseName: "rss"
  RSS:
    mediaType: "application/rss"
    baseName: "rss-drupal"
```

**Comment by adamhstewart** [comment]
something like this is probably going to be the right path (following [custom output formats](https://gohugo.io/templates/output-formats/)): 

```yaml
outputFormats:
  RSS:
    mediaType: "application/rss"
    baseName: "rss"
  RSSDRUPAL:
    mediaType: "application/rss"
    baseName: "rss-drupal"
```

**Comment by adamhstewart** [comment]
small breakthrough...

this config:

```yaml
outputs:
  home:
    - "HTML"
    - "RSS"
    - "rssblog"
    - "rsselm"
    - "rssitunes"
  section:
    - "HTML"
outputFormats:
  RSS:
    mediaType: "application/rss"
    baseName: "rss"
  rssblog:
    mediaType: "application/rss"
    baseName: "rss-blog"
  rsselm:
    mediaType: "application/rss"
    baseName: "rss-elm"
  rssitunes:
    mediaType: "application/rss"
    baseName: "rss-itunes"
```

with corresponding templates at:

`rss.xml`
`home.rssdrupal.xml`
`home.rsselm.xml`
`home.rssitunes.xml`

is getting us the rss URLs that we want.

... now we just need to get those templates to output the right items.
